(cl:in-package core_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          DATA00-VAL
          DATA00
          DATA01-VAL
          DATA01
          DATA02-VAL
          DATA02
          DATA03-VAL
          DATA03
          DATA04-VAL
          DATA04
          DATA05-VAL
          DATA05
          DATA06-VAL
          DATA06
          DATA07-VAL
          DATA07
          DATA08-VAL
          DATA08
          DATA09-VAL
          DATA09
          DATA10-VAL
          DATA10
          DATA11-VAL
          DATA11
          DATA12-VAL
          DATA12
          DATA13-VAL
          DATA13
          DATA14-VAL
          DATA14
          DATA15-VAL
          DATA15
          DATA16-VAL
          DATA16
          DATA17-VAL
          DATA17
          DATA18-VAL
          DATA18
          DATA19-VAL
          DATA19
          DATA20-VAL
          DATA20
          DATA21-VAL
          DATA21
          DATA22-VAL
          DATA22
          DATA23-VAL
          DATA23
          PICK_START-VAL
          PICK_START
))