(cl:in-package core_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          SIZE-VAL
          SIZE
          IMG_X-VAL
          IMG_X
          IMG_Y-VAL
          IMG_Y
          R_SIZE-VAL
          R_SIZE
          B_SIZE-VAL
          B_SIZE
          G_SIZE-VAL
          G_SIZE
          B_OVER-VAL
          B_OVER
          R_IMG_X-VAL
          R_IMG_X
          R_IMG_Y-VAL
          R_IMG_Y
          B_IMG_X-VAL
          B_IMG_X
          B_IMG_Y-VAL
          B_IMG_Y
          G_IMG_X-VAL
          G_IMG_X
          G_IMG_Y-VAL
          G_IMG_Y
))