// Generated by gencpp from file core_msgs/wall_distance.msg
// DO NOT EDIT!


#ifndef CORE_MSGS_MESSAGE_WALL_DISTANCE_H
#define CORE_MSGS_MESSAGE_WALL_DISTANCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace core_msgs
{
template <class ContainerAllocator>
struct wall_distance_
{
  typedef wall_distance_<ContainerAllocator> Type;

  wall_distance_()
    : header()
    , marker_exist(0)
    , marker_x()
    , marker_distance()  {
    }
  wall_distance_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , marker_exist(0)
    , marker_x(_alloc)
    , marker_distance(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _marker_exist_type;
  _marker_exist_type marker_exist;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _marker_x_type;
  _marker_x_type marker_x;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _marker_distance_type;
  _marker_distance_type marker_distance;





  typedef boost::shared_ptr< ::core_msgs::wall_distance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::core_msgs::wall_distance_<ContainerAllocator> const> ConstPtr;

}; // struct wall_distance_

typedef ::core_msgs::wall_distance_<std::allocator<void> > wall_distance;

typedef boost::shared_ptr< ::core_msgs::wall_distance > wall_distancePtr;
typedef boost::shared_ptr< ::core_msgs::wall_distance const> wall_distanceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::core_msgs::wall_distance_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::core_msgs::wall_distance_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace core_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'core_msgs': ['/home/lps/capstone_2/src/core_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::core_msgs::wall_distance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::core_msgs::wall_distance_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::core_msgs::wall_distance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::core_msgs::wall_distance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::core_msgs::wall_distance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::core_msgs::wall_distance_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::core_msgs::wall_distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8af82f0fb4a3c9249aeb4fc459a22c0";
  }

  static const char* value(const ::core_msgs::wall_distance_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8af82f0fb4a3c92ULL;
  static const uint64_t static_value2 = 0x49aeb4fc459a22c0ULL;
};

template<class ContainerAllocator>
struct DataType< ::core_msgs::wall_distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "core_msgs/wall_distance";
  }

  static const char* value(const ::core_msgs::wall_distance_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::core_msgs::wall_distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int32 marker_exist\n\
int32[] marker_x\n\
float32[] marker_distance\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::core_msgs::wall_distance_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::core_msgs::wall_distance_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.marker_exist);
      stream.next(m.marker_x);
      stream.next(m.marker_distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct wall_distance_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::core_msgs::wall_distance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::core_msgs::wall_distance_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "marker_exist: ";
    Printer<int32_t>::stream(s, indent + "  ", v.marker_exist);
    s << indent << "marker_x[]" << std::endl;
    for (size_t i = 0; i < v.marker_x.size(); ++i)
    {
      s << indent << "  marker_x[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.marker_x[i]);
    }
    s << indent << "marker_distance[]" << std::endl;
    for (size_t i = 0; i < v.marker_distance.size(); ++i)
    {
      s << indent << "  marker_distance[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.marker_distance[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CORE_MSGS_MESSAGE_WALL_DISTANCE_H
